name: Update Pixela Habit Graph

on:
  # triggers on any push or pull-request, adjust as you like
  push:
    branches: [ main ]
  # and also once a day at 23:59 UTC as a backup
  schedule:
    - cron: "59 23 * * *"  # runs daily at 11:59 PM UTC

jobs:
  update-habit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update Pixela graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PIXELA_TOKEN: ${{ secrets.PIXELA_TOKEN }}
          # if you want to override your username/graph:
          # USERNAME: "suhaas15"
          # GRAPH_ID: "graph1"
        run: python update_pixela.py
